name: publish

on:
  release:
    types:
      - created

jobs:
  publish:
    runs-on: ubuntu-latest
    environment: release
    permissions:
      id-token: write
      contents: write
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: '3.x'
          cache: poetry
      - run: |
          poetry version ${GITHUB_REF_NAME#v}
          poetry build
      - uses: pypa/gh-action-pypi-publish@release/v1
      - run: gh release upload $GITHUB_REF_NAME dist/*
        env:
          GH_TOKEN: ${{ github.token }}
